---
- name: Add IP range to AWX inventory
  hosts: localhost
  gather_facts: false
  vars:
    awx_url: "http://192.168.1.211:30080"
    awx_token: "qGnWDjPzC9qn4YjZWzivNJCIGoX64h"
    inventory_id: 1
    ip_range_start: 50
    ip_range_end: 150

  tasks:
    - name: Add each IP to AWX inventory
      uri:
        url: "{{ awx_url }}/api/v2/inventories/{{ inventory_id }}/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "192.168.1.{{ item }}"
          enabled: true
          description: "Imported via IP range"
          variables: |
            ansible_host: 192.168.1.{{ item }}
            imported_by: playbook
            source: ip-range
        status_code: 201
        return_content: true
      loop: "{{ range(ip_range_start, ip_range_end + 1) | list }}"
      loop_control:
        label: "192.168.1.{{ item }}"